language: node_js

node_js:
  - "5.10"

before_install:
  - "export CHROME_BIN=/usr/bin/google-chrome"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - npm install angular-cli@webpack
  - npm install

script:
  - ng lint
  - ng test --watch=false

sudo: required
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

notifications:
  webhooks:
    urls:
      - "https://webhooks.gitter.im/e/64e4a7be47fac5f5415d"
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
